FROM golang:1.18.1 AS builder

WORKDIR /app

COPY . .

#RUN go build -o fullcycle
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o fullcycle .

FROM scratch

COPY --from=builder /app/fullcycle /fullcycle

ENTRYPOINT ["/fullcycle"]